module.exports = [
  {
    type: 'input',
    name: 'name',
    message: 'Enter component name...',
  },
  {
    type: 'select',
    name: 'folder',
    message: 'Select screen folder...',
    choices: [
      'Start',
      'ParalaxScroll',
      'VideoCall',
      'CountdownTimer',
      'FortuneWheel',
      'BottomSheet',
      'ColorSelection',
      'StickyElement',
      'AwesomeCarousel',
      'FlatListItemAnimation',
      'FlatGallery',
      'FlatFilms',
      'DotInversion',
      'LongPress',
      'AnimatedSentence',
      'StopWatch',
      'TabBar',
      'FlatListAppearance',
      'CustomSlider',
      'GestureIteractions',
      //ADD MORE SCREENS
    ],
  },
];
